name: Docker Image CI

on:
  push:
    branches: [ main ]
    
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub Registry 🔢
      run: echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login -u '${{ secrets.DOCKERHUB_USERNAME }}' --password-stdin

    - name: Clean up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo du -sh

    - name: Build the Docker image for CPU and push
      run: |
        IMAGE_NAME='${{ secrets.DOCKERHUB_USERNAME }}'/paraphraser_cpu:latest
        docker build . --file Dockerfile.cpu --tag $IMAGE_NAME
        docker push $IMAGE_NAME

    - name: Build the Docker image for GPU and push
      run: |
        IMAGE_NAME='${{ secrets.DOCKERHUB_USERNAME }}'/paraphraser_gpu:latest
        docker build . --file Dockerfile.gpu --tag $IMAGE_NAME
        docker push $IMAGE_NAME

